### PR TITLE
Fix space suffix folder 404

### LINKED ISSUE #3: Get failed when there is space postfix
Failed case:

```
func TestGetSpecial(t *testing.T) {
	ctx := setup(t)
	node, err := fs.Get(ctx, "/CalibreLibrary/Jie Fu _Dai Wei Sen/Geng Jian Yue De Sheng Huo _Jia Ju Pian (Quan Qiu Re Mai  Zui Da Xian Du Rang Ni De Sheng Huo Jian Yue Er Jing Zhi ) (Jia Ju Xi ", FolderKind)
	require.NoError(t, err)
	require.NotNil(t, node)
}
```

```
"...Jia Ju Xi"  # ok
"...Jia Ju Xi " # failed
```

### PR DESCRIPTION
**Pull request by jim3ma**
Fix #3

Signed-off-by: Jim Ma <majinjing3@gmail.com>

### CODE REVIEW

**Comment by K265** [comment]
@jim3ma 
Thanks for your PR.
I think it's better to remove white spaces in *normalizePath*.
see <https://github.com/K265/aliyundrive-go/commit/e2849ecc3cc08b9ab93f91c82a14e7f2c640d06e>.

**Comment by jim3ma** [comment]
> @jim3ma
> Thanks for your PR.
> I think it's better to remove white spaces in _normalizePath_.
> see [e2849ec](https://github.com/K265/aliyundrive-go/commit/e2849ecc3cc08b9ab93f91c82a14e7f2c640d06e).

No, when sync remote to local, the space is lost. The filesystem is not same we uploaded.

**Comment by K265** [comment]
> > @jim3ma
> > Thanks for your PR.
> > I think it's better to remove white spaces in _normalizePath_.
> > see [e2849ec](https://github.com/K265/aliyundrive-go/commit/e2849ecc3cc08b9ab93f91c82a14e7f2c640d06e).
> 
> No, when sync remote to local, the space is lost, file or directory name changed. The filesystem is not same with we uploaded.

@jim3ma 
Can you share that remote folder? 
When I create a folder named " test1 " in the remote, the white spaces will be lost also and became "test1"

**Comment by jim3ma** [comment]
> > > @jim3ma
> > > Thanks for your PR.
> > > I think it's better to remove white spaces in _normalizePath_.
> > > see [e2849ec](https://github.com/K265/aliyundrive-go/commit/e2849ecc3cc08b9ab93f91c82a14e7f2c640d06e).
> > 
> > 
> > No, when sync remote to local, the space is lost, file or directory name changed. The filesystem is not same with we uploaded.
> 
> @jim3ma
> Can you share that remote folder?
> When I create a folder named " test1 " in the remote, the white spaces will be lost also and became "test1"

Use rclone to sync folder, the space is not trimmed.
When create in web, the space removed.

We must keep sdk max compatibility with posix.

**Comment by jim3ma** [comment]
```json
{
  "items": [
    {
      "drive_id": "25095",
      "domain_id": "bj29",
      "file_id": "6110c391950cbea10c344d8686caa3963d014ff8",
      "name": "test ",
      "type": "folder",
      "created_at": "2021-08-09T05:56:33.133Z",
      "updated_at": "2021-08-09T05:56:33.133Z",
      "hidden": false,
      "starred": false,
      "status": "available",
      "parent_file_id": "6110c0aa060833e85a134c339100c59763797098",
      "encrypt_mode": "none"
    },
    {
      "drive_id": "25095",
      "domain_id": "bj29",
      "file_id": "6110c0b0e51d73299a224145aa92c7f750f41dc6",
      "name": "test",
      "type": "folder",
      "created_at": "2021-08-09T05:44:16.413Z",
      "updated_at": "2021-08-09T05:44:16.413Z",
      "hidden": false,
      "starred": false,
      "status": "available",
      "parent_file_id": "6110c0aa060833e85a134c339100c59763797098",
      "encrypt_mode": "none"
    },
    {
      "drive_id": "25095",
      "domain_id": "bj29",
      "file_id": "6110c0bdb29f5991a00d4660bc65dc88481f240f",
      "name": "test.txt",
      "type": "file",
      "content_type": "application/oct-stream",
      "created_at": "2021-08-09T05:44:29.369Z",
      "updated_at": "2021-08-09T05:44:29.711Z",
      "file_extension": "txt",
      "mime_type": "text/plain; charset=utf-8",
      "mime_extension": "txt",
      "hidden": false,
      "size": 27,
      "starred": false,
      "status": "available",
      "upload_id": "76A355F0999E4FF2A1D7455E227D0E6B",
      "parent_file_id": "6110c0aa060833e85a134c339100c59763797098",
      "crc64_hash": "3670425465059604464",
      "content_hash": "9C6C33DBC7BE00ABD0912BF1D0CEF0D699EFB0E4",
      "content_hash_name": "sha1",
      "download_url": "",
      "url": "",
      "category": "doc",
      "encrypt_mode": "none",
      "punish_flag": 0
    }
  ],
  "next_marker": ""
}
```

**Comment by jim3ma** [comment]
```
rclone ls aliyundrive:/test/
       27 test.txt
   242870 test/ssl-handshake-rsa.jpg
   242870 test /ssl-handshake-rsa.jpg
```

**Comment by K265** [comment]
> ```
> # rclone ls aliyundrive:/test/
>        27 test.txt
>    334346 test/ssl-handshake-diffie-hellman.jpg
>    242870 test /ssl-handshake-rsa.jp
> ```
> 
> The space suffix is valid in aliyundrive, I think `get_by_path` has bug when process object with space suffix. This PR fixes this.

@jim3ma 
You're right.
Thanks for your time.

**Pull request merged**
